[package]
name = "account-sys"
version = "0.1.0"
authors = ["a186r <hi.aewalle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethkey = "0.3"
crypto = {path="../crypto", version="0.1.0"}